### ISSUE TITLE
Update binary

### ISSUE THREAD

**Issue by MCMic** [ChristophWurst/kitinerary-bin#1]
Hello, the binary is 3 years old, could you update it?
Also, this kind of tool is mostly useful when it is up to date, because ticket formats change regularly and the software has to adapt. Could we setup some kind of automatic update for the binary when new versions come out?

**Comment by ChristophWurst** [comment]
Fair enough. Would you looking into such an automation?

**Comment by MCMic** [comment]
I have yet to successfully build it by hand first, the docker container for the static build do not build on my machine :disappointed:
