### ISSUE TITLE
PHP8.2: BinaryAdapter::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void

### ISSUE THREAD

**Issue by arnebr** [ChristophWurst/kitinerary-bin#7]
Hallo Christhop,
I get the following error with the package:
`Declaration of ChristophWurst\KItinerary\Bin\BinaryAdapter::setLogger(Psr\Log\LoggerInterface $logger) must be compatible with Psr\Log\LoggerAwareInterface::setLogger(Psr\Log\LoggerInterface $logger): void`

Since psr/log requires a return type since 3.0 a simple fix can be done.

https://github.com/ChristophWurst/kitinerary-bin/blob/46f60f8a9c1861f8f53f7d6b4270b0684a7c736d/src/BinaryAdapter.php#L62

A simple `void` fixes the error
```
public function setLogger(LoggerInterface $logger):void
	{
		$this->logger = $logger;
	}
```

**Comment by kesselb** [comment]
Fixed by #8
